services:

#  _defaults:
#      autowire: true
#      autoconfigure: true
#
#
#  App\Form\ApiRegistrationType:
#    arguments: ['%country_iso%']
#    tags:
#      - { name: form.type, alias: app_user_api_registration }
#
#  App\Form\SettingsType:
#    arguments:
#      $country: '%country_iso%'
#      $isDemo: '%is_demo%'
#      $debug: '%kernel.debug%'
#    tags: [ form.type ]