oneup_flysystem:
  adapters:
    assets:
      awss3v3:
        client: s3_client
        bucket: '%env(S3_BUCKET)%'
        prefix: assets
    product_images:
      awss3v3:
        client: s3_client
        bucket: '%env(S3_BUCKET)%'
        prefix: products
    business_images:
      awss3v3:
        client: s3_client
        bucket: '%env(S3_BUCKET)%'
        prefix: businesses
    store_images:
      awss3v3:
        client: s3_client
        bucket: '%env(S3_BUCKET)%'
        prefix: stores
    listing_images:
      awss3v3:
        client: s3_client
        bucket: '%env(S3_BUCKET)%'
        prefix: listings
    receipts:
      awss3v3:
        client: s3_client
        bucket: '%env(S3_BUCKET)%'
        prefix: receipts
    listing_imports:
      awss3v3:
        client: s3_client
        bucket: '%env(S3_BUCKET)%'
        prefix: listing_imports
    product_imports:
      awss3v3:
        client: s3_client
        bucket: '%env(S3_BUCKET)%'
        prefix: product_imports
    cdn:
      awss3v3:
        client: cdn_s3_client
        bucket: '%env(CDN_S3_BUCKET)%'
        prefix: ''
  filesystems:
    assets:
      adapter: assets
      alias: assets_filesystem
      mount: assets_filesystem
    product_images:
      adapter: product_images
      alias: product_images_filesystem
      mount: product_images_filesystem
    business_images:
      adapter: business_images
      alias: business_images_filesystem
      mount: business_images_filesystem
    store_images:
      adapter: store_images
      alias: store_images_filesystem
      mount: store_images_filesystem
    listing_images:
      adapter: listing_images
      alias: listing_images_filesystem
      mount: listing_images_filesystem
    receipts:
      adapter: receipts
      alias: receipts_filesystem
      mount: receipts_filesystem
    listing_imports:
      adapter: listing_imports
      alias: listing_imports_filesystem
      mount: listing_imports_filesystem
    product_imports:
      adapter: product_imports
      alias: product_imports_filesystem
      mount: product_imports_filesystem
    cdn:
      adapter: cdn
      alias: cdn_filesystem
      mount: cdn_filesystem