twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/address_book.html.twig'
        - '@VichUploader/Form/fields.html.twig'
        - '@TetranzSelect2Entity/Form/fields.html.twig'
    globals:
        #Identity
        astrada_site_name: "%astrada.site_name%"
        astrada_phone: "%astrada.phone%"
        astrada_address: "%astrada.address%"
        astrada_short_description: "%astrada.short_description%"
        astrada_contact_mail: "%astrada.contact_mail%"
        astrada_contact_mail_obfuscated: "%astrada.contact_mail_obfuscated%"
        astrada_from_email: "%astrada.from_email%"
        is_demo: "%is_demo%"
        country_iso: "%country_iso%"
        region_iso: "%region_iso%"
        cart_provider: '@App\Service\CartProviderService'
        settings_manager: "@astrada.settings_manager"
        analytics_disabled: "%kernel.debug%"
        matomo_hostname: "%env(ASTRADA_MATOMO_HOSTNAME)%"
        matomo_site_id: "%env(ASTRADA_MATOMO_SITE_ID)%"
        matomo_checkout_completed_goal_id: "%env(MATOMO_CHECKOUT_COMPLETED_GOAL_ID)%"
        countly_script: "%env(ASTRADA_COUNTLY_SCRIPT)%"
        countly_hostname: "%env(ASTRADA_COUNTLY_HOSTNAME)%"
        countly_app_key: "%env(ASTRADA_COUNTLY_APP_KEY)%"
        cdn_root_url: '%env(CDN_ROOT_URL)%'
        currency_context: "@sylius.context.currency"
        algolia_places_app_id: '%env(ALGOLIA_PLACES_APP_ID)%'
        algolia_places_api_key: '%env(ALGOLIA_PLACES_API_KEY)%'
        algolia_places_address_template: '%env(ALGOLIA_PLACES_ADDRESS_TEMPLATE)%'
        locationiq_access_token: '%env(LOCATIONIQ_ACCESS_TOKEN)%'
        google_api_key: '%env(GOOGLE_API_KEY)%'
        autocomplete_adapter: '%env(ASTRADA_AUTOCOMPLETE_ADAPTER)%'
        geocode_earth_api_key: '%env(GEOCODE_EARTH_API_KEY)%'
        business_caption_cache_annotation: '%business_caption_cache_annotation%'
