<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220218121220 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE address (id SERIAL NOT NULL, name VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, geo geography(GEOMETRY, 4326) NOT NULL, address_country VARCHAR(255) DEFAULT NULL, address_locality VARCHAR(255) DEFAULT NULL, address_region VARCHAR(255) DEFAULT NULL, postal_code VARCHAR(255) DEFAULT NULL, post_office_box_number VARCHAR(255) DEFAULT NULL, street_address VARCHAR(255) NOT NULL, company VARCHAR(255) DEFAULT NULL, telephone VARCHAR(35) DEFAULT NULL, contact_name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN address.telephone IS \'(DC2Type:phone_number)\'');
        $this->addSql('CREATE INDEX idx_address_geo ON address USING gist(geo)');
        $this->addSql('CREATE TABLE api_app (id SERIAL NOT NULL, business_id INT NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(12) NOT NULL, api_key VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8AEC36FBA89DB457 ON api_app (business_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8AEC36FBC912ED9D ON api_app (api_key)');
        $this->addSql('CREATE TABLE api_user (id SERIAL NOT NULL, customer_id INT NOT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled BOOLEAN NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, locale VARCHAR(8) DEFAULT NULL, timezone VARCHAR(64) DEFAULT NULL, roles TEXT NOT NULL, quotes_allowed BOOLEAN DEFAULT \'false\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AC64A0BA92FC23A8 ON api_user (username_canonical)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AC64A0BAA0D96FBF ON api_user (email_canonical)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AC64A0BAC05FB297 ON api_user (confirmation_token)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AC64A0BA9395C3F3 ON api_user (customer_id)');
        $this->addSql('COMMENT ON COLUMN api_user.roles IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE api_user_business (api_user_id INT NOT NULL, business_id INT NOT NULL, PRIMARY KEY(api_user_id, business_id))');
        $this->addSql('CREATE INDEX IDX_40333FB44A50A7F2 ON api_user_business (api_user_id)');
        $this->addSql('CREATE INDEX IDX_40333FB4A89DB457 ON api_user_business (business_id)');
        $this->addSql('CREATE TABLE booking (id SERIAL NOT NULL, topic_id INT DEFAULT NULL, user_id INT DEFAULT NULL, address_id INT DEFAULT NULL, business_id INT DEFAULT NULL, listing_id INT DEFAULT NULL, status SMALLINT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, start_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, validated BOOLEAN DEFAULT \'false\' NOT NULL, new_booking_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, canceled_asker_booking_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, alerted_expiring BOOLEAN DEFAULT \'false\' NOT NULL, message TEXT NOT NULL, distance INT NOT NULL, price_transportation TEXT NOT NULL, price_well_drilling TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E00CEDDE1F55203D ON booking (topic_id)');
        $this->addSql('CREATE INDEX IDX_E00CEDDEA76ED395 ON booking (user_id)');
        $this->addSql('CREATE INDEX IDX_E00CEDDEF5B7AF75 ON booking (address_id)');
        $this->addSql('CREATE INDEX IDX_E00CEDDEA89DB457 ON booking (business_id)');
        $this->addSql('CREATE INDEX IDX_E00CEDDED4619D1A ON booking (listing_id)');
        $this->addSql('CREATE TABLE business (id SERIAL NOT NULL, address_id INT DEFAULT NULL, business_address_id INT DEFAULT NULL, type VARCHAR(255) NOT NULL, owner_type VARCHAR(255) DEFAULT \'legal_entity\' NOT NULL, name VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, enabled BOOLEAN DEFAULT \'false\' NOT NULL, image_name VARCHAR(255) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, telephone VARCHAR(35) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, legal_name VARCHAR(255) DEFAULT NULL, transportation_perimeter_expression VARCHAR(255) DEFAULT \'distance < 300\' NOT NULL, vat_id VARCHAR(255) DEFAULT NULL, additional_properties JSON DEFAULT NULL, state VARCHAR(255) NOT NULL, featured BOOLEAN NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, quotes_allowed BOOLEAN DEFAULT \'false\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8D36E38F5B7AF75 ON business (address_id)');
        $this->addSql('CREATE INDEX IDX_8D36E383514A7DE ON business (business_address_id)');
        $this->addSql('CREATE INDEX business_enabled_index ON business (id, enabled)');
        $this->addSql('CREATE INDEX IDX_8D36E388CDE5729 ON business (type)');
        $this->addSql('COMMENT ON COLUMN business.telephone IS \'(DC2Type:phone_number)\'');
        $this->addSql('COMMENT ON COLUMN business.additional_properties IS \'(DC2Type:json_array)\'');
        $this->addSql('CREATE TABLE business_fulfillment_methods (business_id INT NOT NULL, method_id INT NOT NULL, PRIMARY KEY(business_id, method_id))');
        $this->addSql('CREATE INDEX IDX_EBE2B1C6A89DB457 ON business_fulfillment_methods (business_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EBE2B1C619883967 ON business_fulfillment_methods (method_id)');
        $this->addSql('CREATE TABLE business_closing_rule (business_id INT NOT NULL, rule_id INT NOT NULL, PRIMARY KEY(business_id, rule_id))');
        $this->addSql('CREATE INDEX IDX_83E6936A89DB457 ON business_closing_rule (business_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_83E6936744E0351 ON business_closing_rule (rule_id)');
        $this->addSql('CREATE TABLE business_taxon (business_id INT NOT NULL, taxon_id INT NOT NULL, PRIMARY KEY(business_id, taxon_id))');
        $this->addSql('CREATE INDEX IDX_2586C414A89DB457 ON business_taxon (business_id)');
        $this->addSql('CREATE INDEX IDX_2586C414DE13F470 ON business_taxon (taxon_id)');
        $this->addSql('CREATE TABLE business_fulfillment_method (id SERIAL NOT NULL, type VARCHAR(255) NOT NULL, opening_hours JSON NOT NULL, opening_hours_behavior VARCHAR(16) NOT NULL, options JSON DEFAULT NULL, enabled BOOLEAN DEFAULT \'true\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN business_fulfillment_method.opening_hours IS \'(DC2Type:json_array)\'');
        $this->addSql('COMMENT ON COLUMN business_fulfillment_method.options IS \'(DC2Type:json_array)\'');
        $this->addSql('CREATE TABLE closing_rule (id SERIAL NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reason VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE craue_config_setting (name VARCHAR(255) NOT NULL, section VARCHAR(255) DEFAULT NULL, value VARCHAR(255) DEFAULT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE TABLE delivery (id INT NOT NULL, order_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3781EC108D9F6D38 ON delivery (order_id)');
        $this->addSql('CREATE TABLE listing (id SERIAL NOT NULL, next_renewal_product_id INT DEFAULT NULL, address_id INT DEFAULT NULL, business_id INT DEFAULT NULL, status SMALLINT NOT NULL, certified BOOLEAN DEFAULT NULL, min_duration SMALLINT DEFAULT NULL, max_duration SMALLINT DEFAULT NULL, average_rating SMALLINT DEFAULT NULL, comment_count INT DEFAULT NULL, admin_notation NUMERIC(3, 1) DEFAULT NULL, availabilities_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, telephone VARCHAR(35) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, duration INT DEFAULT NULL, quota INT DEFAULT NULL, auto_renewal BOOLEAN DEFAULT \'false\' NOT NULL, is_default BOOLEAN DEFAULT \'false\' NOT NULL, expiration_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, strategy_code_name VARCHAR(255) DEFAULT \'end_last\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CB0048D41F3B1C5E ON listing (next_renewal_product_id)');
        $this->addSql('CREATE INDEX IDX_CB0048D4F5B7AF75 ON listing (address_id)');
        $this->addSql('CREATE INDEX IDX_CB0048D4A89DB457 ON listing (business_id)');
        $this->addSql('CREATE INDEX status_l_idx ON listing (status)');
        $this->addSql('CREATE INDEX average_rating_idx ON listing (average_rating)');
        $this->addSql('COMMENT ON COLUMN listing.telephone IS \'(DC2Type:phone_number)\'');
        $this->addSql('CREATE TABLE listing_taxon (listing_id INT NOT NULL, taxon_id INT NOT NULL, PRIMARY KEY(listing_id, taxon_id))');
        $this->addSql('CREATE INDEX IDX_AD89FB27D4619D1A ON listing_taxon (listing_id)');
        $this->addSql('CREATE INDEX IDX_AD89FB27DE13F470 ON listing_taxon (taxon_id)');
        $this->addSql('CREATE TABLE listing_availability (id SERIAL NOT NULL, listing_id INT NOT NULL, day DATE NOT NULL, status INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE listing_image (id SERIAL NOT NULL, listing_id INT NOT NULL, image_name VARCHAR(255) DEFAULT NULL, ratio VARCHAR(5) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_33D3DCD3D4619D1A ON listing_image (listing_id)');
        $this->addSql('CREATE TABLE listing_pricing_rule (id SERIAL NOT NULL, rule_set_id INT NOT NULL, type TEXT NOT NULL, expression TEXT NOT NULL, price TEXT NOT NULL, position INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E8FC88738B51FD88 ON listing_pricing_rule (rule_set_id)');
        $this->addSql('CREATE TABLE listing_pricing_rule_set (id SERIAL NOT NULL, business_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, strategy VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2B0BBD97A89DB457 ON listing_pricing_rule_set (business_id)');
        $this->addSql('CREATE TABLE listing_review (id SERIAL NOT NULL, listing_id INT NOT NULL, author_id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, rating INT NOT NULL, comment TEXT DEFAULT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9DBBA015D4619D1A ON listing_review (listing_id)');
        $this->addSql('CREATE INDEX IDX_9DBBA015F675F31B ON listing_review (author_id)');
        $this->addSql('CREATE TABLE listing_subscription (id SERIAL NOT NULL, user_id INT DEFAULT NULL, product_id INT DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, active BOOLEAN NOT NULL, auto_renewal BOOLEAN NOT NULL, reason VARCHAR(255) DEFAULT NULL, strategy VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_26F44AD2A76ED395 ON listing_subscription (user_id)');
        $this->addSql('CREATE INDEX IDX_26F44AD24584665A ON listing_subscription (product_id)');
        $this->addSql('CREATE TABLE listing_translation (id SERIAL NOT NULL, translatable_id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, locale VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E3779C3D2C2AC5D3 ON listing_translation (translatable_id)');
        $this->addSql('CREATE UNIQUE INDEX listing_translation_uniq_trans ON listing_translation (translatable_id, locale)');
        $this->addSql('CREATE TABLE post (id SERIAL NOT NULL, topic_id INT DEFAULT NULL, reply_to_id INT DEFAULT NULL, author_id INT DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, body TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5A8A6C8D77153098 ON post (code)');
        $this->addSql('CREATE INDEX IDX_5A8A6C8D1F55203D ON post (topic_id)');
        $this->addSql('CREATE INDEX IDX_5A8A6C8DFFDF7169 ON post (reply_to_id)');
        $this->addSql('CREATE INDEX IDX_5A8A6C8DF675F31B ON post (author_id)');
        $this->addSql('CREATE TABLE sylius_adjustment (id SERIAL NOT NULL, order_id INT DEFAULT NULL, order_item_id INT DEFAULT NULL, order_item_unit_id INT DEFAULT NULL, type VARCHAR(255) NOT NULL, label VARCHAR(255) DEFAULT NULL, amount INT NOT NULL, is_neutral BOOLEAN NOT NULL, is_locked BOOLEAN NOT NULL, origin_code VARCHAR(255) DEFAULT NULL, details JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_ACA6E0F28D9F6D38 ON sylius_adjustment (order_id)');
        $this->addSql('CREATE INDEX IDX_ACA6E0F2E415FB15 ON sylius_adjustment (order_item_id)');
        $this->addSql('CREATE INDEX IDX_ACA6E0F2F720C233 ON sylius_adjustment (order_item_unit_id)');
        $this->addSql('CREATE TABLE sylius_channel (id SERIAL NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, color VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, enabled BOOLEAN NOT NULL, hostname VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_16C8119E77153098 ON sylius_channel (code)');
        $this->addSql('CREATE INDEX IDX_16C8119EE551C011 ON sylius_channel (hostname)');
        $this->addSql('CREATE TABLE sylius_currency (id SERIAL NOT NULL, code VARCHAR(3) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_96EDD3D077153098 ON sylius_currency (code)');
        $this->addSql('CREATE TABLE sylius_customer (id SERIAL NOT NULL, customer_group_id INT DEFAULT NULL, default_address_id INT DEFAULT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, birthday TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, gender VARCHAR(1) DEFAULT \'u\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, phone_number VARCHAR(255) DEFAULT NULL, subscribed_to_newsletter BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7E82D5E6E7927C74 ON sylius_customer (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7E82D5E6A0D96FBF ON sylius_customer (email_canonical)');
        $this->addSql('CREATE INDEX IDX_7E82D5E6D2919A68 ON sylius_customer (customer_group_id)');
        $this->addSql('CREATE INDEX IDX_7E82D5E6BD94FB16 ON sylius_customer (default_address_id)');
        $this->addSql('CREATE TABLE sylius_customer_address (customer_id INT NOT NULL, address_id INT NOT NULL, PRIMARY KEY(customer_id, address_id))');
        $this->addSql('CREATE INDEX IDX_D0D865859395C3F3 ON sylius_customer_address (customer_id)');
        $this->addSql('CREATE INDEX IDX_D0D86585F5B7AF75 ON sylius_customer_address (address_id)');
        $this->addSql('CREATE TABLE sylius_customer_group (id SERIAL NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7FCF9B0577153098 ON sylius_customer_group (code)');
        $this->addSql('CREATE TABLE sylius_exchange_rate (id SERIAL NOT NULL, source_currency INT NOT NULL, target_currency INT NOT NULL, ratio NUMERIC(10, 5) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5F52B852A76BEED ON sylius_exchange_rate (source_currency)');
        $this->addSql('CREATE INDEX IDX_5F52B85B3FD5856 ON sylius_exchange_rate (target_currency)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5F52B852A76BEEDB3FD5856 ON sylius_exchange_rate (source_currency, target_currency)');
        $this->addSql('CREATE TABLE sylius_locale (id SERIAL NOT NULL, code VARCHAR(12) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7BA1286477153098 ON sylius_locale (code)');
        $this->addSql('CREATE TABLE sylius_order (id SERIAL NOT NULL, business_id INT DEFAULT NULL, shipping_address_id INT DEFAULT NULL, billing_address_id INT DEFAULT NULL, channel_id INT DEFAULT NULL, customer_id INT DEFAULT NULL, number VARCHAR(255) DEFAULT NULL, notes TEXT DEFAULT NULL, state VARCHAR(255) NOT NULL, checkout_completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, items_total INT NOT NULL, adjustments_total INT NOT NULL, total INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, takeaway BOOLEAN DEFAULT \'false\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6196A1F996901F54 ON sylius_order (number)');
        $this->addSql('CREATE INDEX IDX_6196A1F9A89DB457 ON sylius_order (business_id)');
        $this->addSql('CREATE INDEX IDX_6196A1F94D4CFF2B ON sylius_order (shipping_address_id)');
        $this->addSql('CREATE INDEX IDX_6196A1F979D0C0E4 ON sylius_order (billing_address_id)');
        $this->addSql('CREATE INDEX IDX_6196A1F972F5A1AA ON sylius_order (channel_id)');
        $this->addSql('CREATE INDEX IDX_6196A1F99395C3F3 ON sylius_order (customer_id)');
        $this->addSql('CREATE INDEX IDX_6196A1F9A393D2FB43625D9F ON sylius_order (state, updated_at)');
        $this->addSql('CREATE TABLE sylius_order_event (id SERIAL NOT NULL, aggregate_id INT DEFAULT NULL, type VARCHAR(255) NOT NULL, data JSON NOT NULL, metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1F7207A3D0BBCCBE ON sylius_order_event (aggregate_id)');
        $this->addSql('COMMENT ON COLUMN sylius_order_event.data IS \'(DC2Type:json_array)\'');
        $this->addSql('COMMENT ON COLUMN sylius_order_event.metadata IS \'(DC2Type:json_array)\'');
        $this->addSql('CREATE TABLE sylius_order_item (id SERIAL NOT NULL, order_id INT NOT NULL, variant_id INT NOT NULL, quantity INT NOT NULL, unit_price INT NOT NULL, units_total INT NOT NULL, adjustments_total INT NOT NULL, total INT NOT NULL, is_immutable BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_77B587ED8D9F6D38 ON sylius_order_item (order_id)');
        $this->addSql('CREATE INDEX IDX_77B587ED3B69A9AF ON sylius_order_item (variant_id)');
        $this->addSql('CREATE TABLE sylius_order_item_unit (id SERIAL NOT NULL, order_item_id INT NOT NULL, adjustments_total INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_82BF226EE415FB15 ON sylius_order_item_unit (order_item_id)');
        $this->addSql('CREATE TABLE sylius_order_sequence (id SERIAL NOT NULL, idx INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE sylius_payment (id SERIAL NOT NULL, method_id INT DEFAULT NULL, order_id INT NOT NULL, currency_code VARCHAR(3) NOT NULL, amount INT NOT NULL, state VARCHAR(255) NOT NULL, details JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D9191BD419883967 ON sylius_payment (method_id)');
        $this->addSql('CREATE INDEX IDX_D9191BD48D9F6D38 ON sylius_payment (order_id)');
        $this->addSql('COMMENT ON COLUMN sylius_payment.details IS \'(DC2Type:json_array)\'');
        $this->addSql('CREATE TABLE sylius_payment_method (id SERIAL NOT NULL, code VARCHAR(255) NOT NULL, environment VARCHAR(255) DEFAULT NULL, is_enabled BOOLEAN NOT NULL, position INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A75B0B0D77153098 ON sylius_payment_method (code)');
        $this->addSql('CREATE TABLE sylius_payment_method_translation (id SERIAL NOT NULL, translatable_id INT NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, instructions TEXT DEFAULT NULL, locale VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_966BE3A12C2AC5D3 ON sylius_payment_method_translation (translatable_id)');
        $this->addSql('CREATE UNIQUE INDEX sylius_payment_method_translation_uniq_trans ON sylius_payment_method_translation (translatable_id, locale)');
        $this->addSql('CREATE TABLE sylius_product (id SERIAL NOT NULL, business_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, enabled BOOLEAN NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, type VARCHAR(255) DEFAULT \'common\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_677B9B7477153098 ON sylius_product (code)');
        $this->addSql('CREATE INDEX IDX_677B9B74A89DB457 ON sylius_product (business_id)');
        $this->addSql('CREATE TABLE sylius_product_association (id SERIAL NOT NULL, association_type_id INT NOT NULL, product_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_48E9CDABB1E1C39 ON sylius_product_association (association_type_id)');
        $this->addSql('CREATE INDEX IDX_48E9CDAB4584665A ON sylius_product_association (product_id)');
        $this->addSql('CREATE UNIQUE INDEX product_association_idx ON sylius_product_association (product_id, association_type_id)');
        $this->addSql('CREATE TABLE sylius_product_association_product (association_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY(association_id, product_id))');
        $this->addSql('CREATE INDEX IDX_A427B983EFB9C8A5 ON sylius_product_association_product (association_id)');
        $this->addSql('CREATE INDEX IDX_A427B9834584665A ON sylius_product_association_product (product_id)');
        $this->addSql('CREATE TABLE sylius_product_association_type (id SERIAL NOT NULL, code VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CCB8914C77153098 ON sylius_product_association_type (code)');
        $this->addSql('CREATE TABLE sylius_product_association_type_translation (id SERIAL NOT NULL, translatable_id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, locale VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4F618E52C2AC5D3 ON sylius_product_association_type_translation (translatable_id)');
        $this->addSql('CREATE UNIQUE INDEX sylius_product_association_type_translation_uniq_trans ON sylius_product_association_type_translation (translatable_id, locale)');
        $this->addSql('CREATE TABLE sylius_product_attribute (id SERIAL NOT NULL, code VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, storage_type VARCHAR(255) NOT NULL, configuration TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, position INT NOT NULL, translatable BOOLEAN DEFAULT \'true\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BFAF484A77153098 ON sylius_product_attribute (code)');
        $this->addSql('COMMENT ON COLUMN sylius_product_attribute.configuration IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE sylius_product_attribute_translation (id SERIAL NOT NULL, translatable_id INT NOT NULL, name VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_93850EBA2C2AC5D3 ON sylius_product_attribute_translation (translatable_id)');
        $this->addSql('CREATE UNIQUE INDEX sylius_product_attribute_translation_uniq_trans ON sylius_product_attribute_translation (translatable_id, locale)');
        $this->addSql('CREATE TABLE sylius_product_attribute_value (id SERIAL NOT NULL, product_id INT NOT NULL, attribute_id INT NOT NULL, locale_code VARCHAR(255) DEFAULT NULL, text_value TEXT DEFAULT NULL, boolean_value BOOLEAN DEFAULT NULL, integer_value INT DEFAULT NULL, float_value DOUBLE PRECISION DEFAULT NULL, datetime_value TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_value DATE DEFAULT NULL, json_value JSON DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8A053E544584665A ON sylius_product_attribute_value (product_id)');
        $this->addSql('CREATE INDEX IDX_8A053E54B6E62EFA ON sylius_product_attribute_value (attribute_id)');
        $this->addSql('COMMENT ON COLUMN sylius_product_attribute_value.json_value IS \'(DC2Type:json_array)\'');
        $this->addSql('CREATE TABLE sylius_product_image (id SERIAL NOT NULL, product_id INT NOT NULL, image_name VARCHAR(255) DEFAULT NULL, ratio VARCHAR(5) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_88C64B2D4584665A ON sylius_product_image (product_id)');
        $this->addSql('CREATE TABLE sylius_product_option (id SERIAL NOT NULL, business_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, position INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, strategy VARCHAR(255) DEFAULT \'free\' NOT NULL, additional BOOLEAN NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, values_range NUMRANGE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E4C0EBEF77153098 ON sylius_product_option (code)');
        $this->addSql('CREATE INDEX IDX_E4C0EBEFA89DB457 ON sylius_product_option (business_id)');
        $this->addSql('COMMENT ON COLUMN sylius_product_option.values_range IS \'(DC2Type:numrange)\'');
        $this->addSql('CREATE TABLE sylius_product_option_translation (id SERIAL NOT NULL, translatable_id INT NOT NULL, name VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CBA491AD2C2AC5D3 ON sylius_product_option_translation (translatable_id)');
        $this->addSql('CREATE UNIQUE INDEX sylius_product_option_translation_uniq_trans ON sylius_product_option_translation (translatable_id, locale)');
        $this->addSql('CREATE TABLE sylius_product_option_value (id SERIAL NOT NULL, option_id INT NOT NULL, code VARCHAR(255) NOT NULL, price INT NOT NULL, enabled BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F7FF7D4B77153098 ON sylius_product_option_value (code)');
        $this->addSql('CREATE INDEX IDX_F7FF7D4BA7C41D6F ON sylius_product_option_value (option_id)');
        $this->addSql('CREATE TABLE sylius_product_option_value_translation (id SERIAL NOT NULL, translatable_id INT NOT NULL, value VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8D4382DC2C2AC5D3 ON sylius_product_option_value_translation (translatable_id)');
        $this->addSql('CREATE UNIQUE INDEX sylius_product_option_value_translation_uniq_trans ON sylius_product_option_value_translation (translatable_id, locale)');
        $this->addSql('CREATE TABLE sylius_product_options (id SERIAL NOT NULL, product_id INT NOT NULL, option_id INT NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2B5FF0094584665A ON sylius_product_options (product_id)');
        $this->addSql('CREATE INDEX IDX_2B5FF009A7C41D6F ON sylius_product_options (option_id)');
        $this->addSql('CREATE UNIQUE INDEX sylius_product_option_unique ON sylius_product_options (product_id, option_id)');
        $this->addSql('CREATE TABLE sylius_product_taxon (id SERIAL NOT NULL, product_id INT NOT NULL, taxon_id INT NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_169C6CD94584665A ON sylius_product_taxon (product_id)');
        $this->addSql('CREATE INDEX IDX_169C6CD9DE13F470 ON sylius_product_taxon (taxon_id)');
        $this->addSql('CREATE UNIQUE INDEX sylius_product_taxon_unique ON sylius_product_taxon (product_id, taxon_id)');
        $this->addSql('CREATE TABLE sylius_product_translation (id SERIAL NOT NULL, translatable_id INT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, meta_keywords VARCHAR(255) DEFAULT NULL, meta_description VARCHAR(255) DEFAULT NULL, locale VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_105A9082C2AC5D3 ON sylius_product_translation (translatable_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_105A9084180C698989D9B62 ON sylius_product_translation (locale, slug)');
        $this->addSql('CREATE UNIQUE INDEX sylius_product_translation_uniq_trans ON sylius_product_translation (translatable_id, locale)');
        $this->addSql('CREATE TABLE sylius_product_variant (id SERIAL NOT NULL, product_id INT NOT NULL, code VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, position INT NOT NULL, enabled BOOLEAN NOT NULL, price INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A29B52377153098 ON sylius_product_variant (code)');
        $this->addSql('CREATE INDEX IDX_A29B5234584665A ON sylius_product_variant (product_id)');
        $this->addSql('CREATE TABLE sylius_product_variant_option_value (id SERIAL NOT NULL, variant_id INT NOT NULL, option_value_id INT NOT NULL, quantity INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_76CDAFA13B69A9AF ON sylius_product_variant_option_value (variant_id)');
        $this->addSql('CREATE INDEX IDX_76CDAFA1D957CA06 ON sylius_product_variant_option_value (option_value_id)');
        $this->addSql('CREATE UNIQUE INDEX sylius_product_variant_option_value_unique ON sylius_product_variant_option_value (variant_id, option_value_id)');
        $this->addSql('CREATE TABLE sylius_product_variant_translation (id SERIAL NOT NULL, translatable_id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, locale VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8DC18EDC2C2AC5D3 ON sylius_product_variant_translation (translatable_id)');
        $this->addSql('CREATE UNIQUE INDEX sylius_product_variant_translation_uniq_trans ON sylius_product_variant_translation (translatable_id, locale)');
        $this->addSql('CREATE TABLE sylius_taxon (id SERIAL NOT NULL, tree_root INT DEFAULT NULL, parent_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, tree_left INT NOT NULL, tree_right INT NOT NULL, tree_level INT NOT NULL, position INT NOT NULL, enabled BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CFD811CA77153098 ON sylius_taxon (code)');
        $this->addSql('CREATE INDEX IDX_CFD811CAA977936C ON sylius_taxon (tree_root)');
        $this->addSql('CREATE INDEX IDX_CFD811CA727ACA70 ON sylius_taxon (parent_id)');
        $this->addSql('CREATE TABLE sylius_taxon_translation (id SERIAL NOT NULL, translatable_id INT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, locale VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1487DFCF2C2AC5D3 ON sylius_taxon_translation (translatable_id)');
        $this->addSql('CREATE UNIQUE INDEX slug_uidx ON sylius_taxon_translation (locale, slug)');
        $this->addSql('CREATE UNIQUE INDEX sylius_taxon_translation_uniq_trans ON sylius_taxon_translation (translatable_id, locale)');
        $this->addSql('CREATE TABLE task (id SERIAL NOT NULL, next_task_id INT DEFAULT NULL, previous_task_id INT DEFAULT NULL, delivery_id INT DEFAULT NULL, address_id INT NOT NULL, type VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, done_after TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, done_before TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, comments TEXT DEFAULT NULL, metadata JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_527EDB254F382B24 ON task (next_task_id)');
        $this->addSql('CREATE INDEX IDX_527EDB25BC2D6B55 ON task (previous_task_id)');
        $this->addSql('CREATE INDEX IDX_527EDB2512136921 ON task (delivery_id)');
        $this->addSql('CREATE INDEX IDX_527EDB25F5B7AF75 ON task (address_id)');
        $this->addSql('COMMENT ON COLUMN task.metadata IS \'(DC2Type:json_array)\'');
        $this->addSql('CREATE TABLE task_collection (id SERIAL NOT NULL, distance INT NOT NULL, duration INT NOT NULL, polyline TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE task_collection_item (id SERIAL NOT NULL, parent_id INT DEFAULT NULL, task_id INT DEFAULT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_13199EFF727ACA70 ON task_collection_item (parent_id)');
        $this->addSql('CREATE INDEX IDX_13199EFF8DB60186 ON task_collection_item (task_id)');
        $this->addSql('CREATE UNIQUE INDEX task_collection_item_unique ON task_collection_item (parent_id, task_id)');
        $this->addSql('CREATE TABLE topic (id SERIAL NOT NULL, main_post_id INT DEFAULT NULL, author_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, post_count INT NOT NULL, view_count INT NOT NULL, last_post_created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9D40DE1B77153098 ON topic (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9D40DE1BBFC2AAC5 ON topic (main_post_id)');
        $this->addSql('CREATE INDEX IDX_9D40DE1BF675F31B ON topic (author_id)');
        $this->addSql('CREATE TABLE topic_followers (topic_id INT NOT NULL, customerinterface_id INT NOT NULL, PRIMARY KEY(topic_id, customerinterface_id))');
        $this->addSql('CREATE INDEX IDX_6D9D691F1F55203D ON topic_followers (topic_id)');
        $this->addSql('CREATE INDEX IDX_6D9D691FF6FD7074 ON topic_followers (customerinterface_id)');
        $this->addSql('CREATE TABLE welldesign (id SERIAL NOT NULL, listing_id INT DEFAULT NULL, pipe_diameter VARCHAR(50) DEFAULT NULL, depth_from SMALLINT NOT NULL, depth_to SMALLINT NOT NULL, drilling_kit VARCHAR(50) DEFAULT NULL, transportation_cost TEXT NOT NULL, well_cost TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_56345A8AD4619D1A ON welldesign (listing_id)');
        $this->addSql('ALTER TABLE api_app ADD CONSTRAINT FK_8AEC36FBA89DB457 FOREIGN KEY (business_id) REFERENCES business (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE api_user ADD CONSTRAINT FK_AC64A0BA9395C3F3 FOREIGN KEY (customer_id) REFERENCES sylius_customer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE api_user_business ADD CONSTRAINT FK_40333FB44A50A7F2 FOREIGN KEY (api_user_id) REFERENCES api_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE api_user_business ADD CONSTRAINT FK_40333FB4A89DB457 FOREIGN KEY (business_id) REFERENCES business (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE1F55203D FOREIGN KEY (topic_id) REFERENCES topic (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEA76ED395 FOREIGN KEY (user_id) REFERENCES api_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEF5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEA89DB457 FOREIGN KEY (business_id) REFERENCES business (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDED4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE business ADD CONSTRAINT FK_8D36E38F5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE business ADD CONSTRAINT FK_8D36E383514A7DE FOREIGN KEY (business_address_id) REFERENCES address (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE business_fulfillment_methods ADD CONSTRAINT FK_EBE2B1C6A89DB457 FOREIGN KEY (business_id) REFERENCES business (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE business_fulfillment_methods ADD CONSTRAINT FK_EBE2B1C619883967 FOREIGN KEY (method_id) REFERENCES business_fulfillment_method (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE business_closing_rule ADD CONSTRAINT FK_83E6936A89DB457 FOREIGN KEY (business_id) REFERENCES business (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE business_closing_rule ADD CONSTRAINT FK_83E6936744E0351 FOREIGN KEY (rule_id) REFERENCES closing_rule (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE business_taxon ADD CONSTRAINT FK_2586C414A89DB457 FOREIGN KEY (business_id) REFERENCES business (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE business_taxon ADD CONSTRAINT FK_2586C414DE13F470 FOREIGN KEY (taxon_id) REFERENCES sylius_taxon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE delivery ADD CONSTRAINT FK_3781EC108D9F6D38 FOREIGN KEY (order_id) REFERENCES sylius_order (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE delivery ADD CONSTRAINT FK_3781EC10BF396750 FOREIGN KEY (id) REFERENCES task_collection (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE listing ADD CONSTRAINT FK_CB0048D41F3B1C5E FOREIGN KEY (next_renewal_product_id) REFERENCES listing (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE listing ADD CONSTRAINT FK_CB0048D4F5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE listing ADD CONSTRAINT FK_CB0048D4A89DB457 FOREIGN KEY (business_id) REFERENCES business (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE listing_taxon ADD CONSTRAINT FK_AD89FB27D4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE listing_taxon ADD CONSTRAINT FK_AD89FB27DE13F470 FOREIGN KEY (taxon_id) REFERENCES sylius_taxon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE listing_image ADD CONSTRAINT FK_33D3DCD3D4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE listing_pricing_rule ADD CONSTRAINT FK_E8FC88738B51FD88 FOREIGN KEY (rule_set_id) REFERENCES listing_pricing_rule_set (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE listing_pricing_rule_set ADD CONSTRAINT FK_2B0BBD97A89DB457 FOREIGN KEY (business_id) REFERENCES business (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE listing_review ADD CONSTRAINT FK_9DBBA015D4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE listing_review ADD CONSTRAINT FK_9DBBA015F675F31B FOREIGN KEY (author_id) REFERENCES sylius_customer (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE listing_subscription ADD CONSTRAINT FK_26F44AD2A76ED395 FOREIGN KEY (user_id) REFERENCES api_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE listing_subscription ADD CONSTRAINT FK_26F44AD24584665A FOREIGN KEY (product_id) REFERENCES listing (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE listing_translation ADD CONSTRAINT FK_E3779C3D2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES listing (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D1F55203D FOREIGN KEY (topic_id) REFERENCES topic (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8DFFDF7169 FOREIGN KEY (reply_to_id) REFERENCES post (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8DF675F31B FOREIGN KEY (author_id) REFERENCES sylius_customer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_adjustment ADD CONSTRAINT FK_ACA6E0F28D9F6D38 FOREIGN KEY (order_id) REFERENCES sylius_order (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_adjustment ADD CONSTRAINT FK_ACA6E0F2E415FB15 FOREIGN KEY (order_item_id) REFERENCES sylius_order_item (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_adjustment ADD CONSTRAINT FK_ACA6E0F2F720C233 FOREIGN KEY (order_item_unit_id) REFERENCES sylius_order_item_unit (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_customer ADD CONSTRAINT FK_7E82D5E6D2919A68 FOREIGN KEY (customer_group_id) REFERENCES sylius_customer_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_customer ADD CONSTRAINT FK_7E82D5E6BD94FB16 FOREIGN KEY (default_address_id) REFERENCES address (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_customer_address ADD CONSTRAINT FK_D0D865859395C3F3 FOREIGN KEY (customer_id) REFERENCES sylius_customer (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_customer_address ADD CONSTRAINT FK_D0D86585F5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_exchange_rate ADD CONSTRAINT FK_5F52B852A76BEED FOREIGN KEY (source_currency) REFERENCES sylius_currency (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_exchange_rate ADD CONSTRAINT FK_5F52B85B3FD5856 FOREIGN KEY (target_currency) REFERENCES sylius_currency (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_order ADD CONSTRAINT FK_6196A1F9A89DB457 FOREIGN KEY (business_id) REFERENCES business (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_order ADD CONSTRAINT FK_6196A1F94D4CFF2B FOREIGN KEY (shipping_address_id) REFERENCES address (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_order ADD CONSTRAINT FK_6196A1F979D0C0E4 FOREIGN KEY (billing_address_id) REFERENCES address (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_order ADD CONSTRAINT FK_6196A1F972F5A1AA FOREIGN KEY (channel_id) REFERENCES sylius_channel (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_order ADD CONSTRAINT FK_6196A1F99395C3F3 FOREIGN KEY (customer_id) REFERENCES sylius_customer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_order_event ADD CONSTRAINT FK_1F7207A3D0BBCCBE FOREIGN KEY (aggregate_id) REFERENCES sylius_order (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_order_item ADD CONSTRAINT FK_77B587ED8D9F6D38 FOREIGN KEY (order_id) REFERENCES sylius_order (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_order_item ADD CONSTRAINT FK_77B587ED3B69A9AF FOREIGN KEY (variant_id) REFERENCES sylius_product_variant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_order_item_unit ADD CONSTRAINT FK_82BF226EE415FB15 FOREIGN KEY (order_item_id) REFERENCES sylius_order_item (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_payment ADD CONSTRAINT FK_D9191BD419883967 FOREIGN KEY (method_id) REFERENCES sylius_payment_method (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_payment ADD CONSTRAINT FK_D9191BD48D9F6D38 FOREIGN KEY (order_id) REFERENCES sylius_order (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_payment_method_translation ADD CONSTRAINT FK_966BE3A12C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES sylius_payment_method (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product ADD CONSTRAINT FK_677B9B74A89DB457 FOREIGN KEY (business_id) REFERENCES business (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product_association ADD CONSTRAINT FK_48E9CDABB1E1C39 FOREIGN KEY (association_type_id) REFERENCES sylius_product_association_type (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product_association ADD CONSTRAINT FK_48E9CDAB4584665A FOREIGN KEY (product_id) REFERENCES sylius_product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product_association_product ADD CONSTRAINT FK_A427B983EFB9C8A5 FOREIGN KEY (association_id) REFERENCES sylius_product_association (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product_association_product ADD CONSTRAINT FK_A427B9834584665A FOREIGN KEY (product_id) REFERENCES sylius_product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product_association_type_translation ADD CONSTRAINT FK_4F618E52C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES sylius_product_association_type (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product_attribute_translation ADD CONSTRAINT FK_93850EBA2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES sylius_product_attribute (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product_attribute_value ADD CONSTRAINT FK_8A053E544584665A FOREIGN KEY (product_id) REFERENCES sylius_product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product_attribute_value ADD CONSTRAINT FK_8A053E54B6E62EFA FOREIGN KEY (attribute_id) REFERENCES sylius_product_attribute (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product_image ADD CONSTRAINT FK_88C64B2D4584665A FOREIGN KEY (product_id) REFERENCES sylius_product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product_option ADD CONSTRAINT FK_E4C0EBEFA89DB457 FOREIGN KEY (business_id) REFERENCES business (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product_option_translation ADD CONSTRAINT FK_CBA491AD2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES sylius_product_option (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product_option_value ADD CONSTRAINT FK_F7FF7D4BA7C41D6F FOREIGN KEY (option_id) REFERENCES sylius_product_option (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product_option_value_translation ADD CONSTRAINT FK_8D4382DC2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES sylius_product_option_value (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product_options ADD CONSTRAINT FK_2B5FF0094584665A FOREIGN KEY (product_id) REFERENCES sylius_product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product_options ADD CONSTRAINT FK_2B5FF009A7C41D6F FOREIGN KEY (option_id) REFERENCES sylius_product_option (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product_taxon ADD CONSTRAINT FK_169C6CD94584665A FOREIGN KEY (product_id) REFERENCES sylius_product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product_taxon ADD CONSTRAINT FK_169C6CD9DE13F470 FOREIGN KEY (taxon_id) REFERENCES sylius_taxon (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product_translation ADD CONSTRAINT FK_105A9082C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES sylius_product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product_variant ADD CONSTRAINT FK_A29B5234584665A FOREIGN KEY (product_id) REFERENCES sylius_product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product_variant_option_value ADD CONSTRAINT FK_76CDAFA13B69A9AF FOREIGN KEY (variant_id) REFERENCES sylius_product_variant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product_variant_option_value ADD CONSTRAINT FK_76CDAFA1D957CA06 FOREIGN KEY (option_value_id) REFERENCES sylius_product_option_value (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_product_variant_translation ADD CONSTRAINT FK_8DC18EDC2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES sylius_product_variant (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_taxon ADD CONSTRAINT FK_CFD811CAA977936C FOREIGN KEY (tree_root) REFERENCES sylius_taxon (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_taxon ADD CONSTRAINT FK_CFD811CA727ACA70 FOREIGN KEY (parent_id) REFERENCES sylius_taxon (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sylius_taxon_translation ADD CONSTRAINT FK_1487DFCF2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES sylius_taxon (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB254F382B24 FOREIGN KEY (next_task_id) REFERENCES task (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25BC2D6B55 FOREIGN KEY (previous_task_id) REFERENCES task (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB2512136921 FOREIGN KEY (delivery_id) REFERENCES delivery (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25F5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE task_collection_item ADD CONSTRAINT FK_13199EFF727ACA70 FOREIGN KEY (parent_id) REFERENCES task_collection (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE task_collection_item ADD CONSTRAINT FK_13199EFF8DB60186 FOREIGN KEY (task_id) REFERENCES task (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE topic ADD CONSTRAINT FK_9D40DE1BBFC2AAC5 FOREIGN KEY (main_post_id) REFERENCES post (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE topic ADD CONSTRAINT FK_9D40DE1BF675F31B FOREIGN KEY (author_id) REFERENCES sylius_customer (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE topic_followers ADD CONSTRAINT FK_6D9D691F1F55203D FOREIGN KEY (topic_id) REFERENCES topic (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE topic_followers ADD CONSTRAINT FK_6D9D691FF6FD7074 FOREIGN KEY (customerinterface_id) REFERENCES sylius_customer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE welldesign ADD CONSTRAINT FK_56345A8AD4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE SCHEMA topology');
        $this->addSql('CREATE SCHEMA tiger');
        $this->addSql('CREATE SCHEMA tiger_data');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDEF5B7AF75');
        $this->addSql('ALTER TABLE business DROP CONSTRAINT FK_8D36E38F5B7AF75');
        $this->addSql('ALTER TABLE business DROP CONSTRAINT FK_8D36E383514A7DE');
        $this->addSql('ALTER TABLE listing DROP CONSTRAINT FK_CB0048D4F5B7AF75');
        $this->addSql('ALTER TABLE sylius_customer DROP CONSTRAINT FK_7E82D5E6BD94FB16');
        $this->addSql('ALTER TABLE sylius_customer_address DROP CONSTRAINT FK_D0D86585F5B7AF75');
        $this->addSql('ALTER TABLE sylius_order DROP CONSTRAINT FK_6196A1F94D4CFF2B');
        $this->addSql('ALTER TABLE sylius_order DROP CONSTRAINT FK_6196A1F979D0C0E4');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25F5B7AF75');
        $this->addSql('ALTER TABLE api_user_business DROP CONSTRAINT FK_40333FB44A50A7F2');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDEA76ED395');
        $this->addSql('ALTER TABLE listing_subscription DROP CONSTRAINT FK_26F44AD2A76ED395');
        $this->addSql('ALTER TABLE api_app DROP CONSTRAINT FK_8AEC36FBA89DB457');
        $this->addSql('ALTER TABLE api_user_business DROP CONSTRAINT FK_40333FB4A89DB457');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDEA89DB457');
        $this->addSql('ALTER TABLE business_fulfillment_methods DROP CONSTRAINT FK_EBE2B1C6A89DB457');
        $this->addSql('ALTER TABLE business_closing_rule DROP CONSTRAINT FK_83E6936A89DB457');
        $this->addSql('ALTER TABLE business_taxon DROP CONSTRAINT FK_2586C414A89DB457');
        $this->addSql('ALTER TABLE listing DROP CONSTRAINT FK_CB0048D4A89DB457');
        $this->addSql('ALTER TABLE listing_pricing_rule_set DROP CONSTRAINT FK_2B0BBD97A89DB457');
        $this->addSql('ALTER TABLE sylius_order DROP CONSTRAINT FK_6196A1F9A89DB457');
        $this->addSql('ALTER TABLE sylius_product DROP CONSTRAINT FK_677B9B74A89DB457');
        $this->addSql('ALTER TABLE sylius_product_option DROP CONSTRAINT FK_E4C0EBEFA89DB457');
        $this->addSql('ALTER TABLE business_fulfillment_methods DROP CONSTRAINT FK_EBE2B1C619883967');
        $this->addSql('ALTER TABLE business_closing_rule DROP CONSTRAINT FK_83E6936744E0351');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB2512136921');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDED4619D1A');
        $this->addSql('ALTER TABLE listing DROP CONSTRAINT FK_CB0048D41F3B1C5E');
        $this->addSql('ALTER TABLE listing_taxon DROP CONSTRAINT FK_AD89FB27D4619D1A');
        $this->addSql('ALTER TABLE listing_image DROP CONSTRAINT FK_33D3DCD3D4619D1A');
        $this->addSql('ALTER TABLE listing_review DROP CONSTRAINT FK_9DBBA015D4619D1A');
        $this->addSql('ALTER TABLE listing_subscription DROP CONSTRAINT FK_26F44AD24584665A');
        $this->addSql('ALTER TABLE listing_translation DROP CONSTRAINT FK_E3779C3D2C2AC5D3');
        $this->addSql('ALTER TABLE welldesign DROP CONSTRAINT FK_56345A8AD4619D1A');
        $this->addSql('ALTER TABLE listing_pricing_rule DROP CONSTRAINT FK_E8FC88738B51FD88');
        $this->addSql('ALTER TABLE post DROP CONSTRAINT FK_5A8A6C8DFFDF7169');
        $this->addSql('ALTER TABLE topic DROP CONSTRAINT FK_9D40DE1BBFC2AAC5');
        $this->addSql('ALTER TABLE sylius_order DROP CONSTRAINT FK_6196A1F972F5A1AA');
        $this->addSql('ALTER TABLE sylius_exchange_rate DROP CONSTRAINT FK_5F52B852A76BEED');
        $this->addSql('ALTER TABLE sylius_exchange_rate DROP CONSTRAINT FK_5F52B85B3FD5856');
        $this->addSql('ALTER TABLE api_user DROP CONSTRAINT FK_AC64A0BA9395C3F3');
        $this->addSql('ALTER TABLE listing_review DROP CONSTRAINT FK_9DBBA015F675F31B');
        $this->addSql('ALTER TABLE post DROP CONSTRAINT FK_5A8A6C8DF675F31B');
        $this->addSql('ALTER TABLE sylius_customer_address DROP CONSTRAINT FK_D0D865859395C3F3');
        $this->addSql('ALTER TABLE sylius_order DROP CONSTRAINT FK_6196A1F99395C3F3');
        $this->addSql('ALTER TABLE topic DROP CONSTRAINT FK_9D40DE1BF675F31B');
        $this->addSql('ALTER TABLE topic_followers DROP CONSTRAINT FK_6D9D691FF6FD7074');
        $this->addSql('ALTER TABLE sylius_customer DROP CONSTRAINT FK_7E82D5E6D2919A68');
        $this->addSql('ALTER TABLE delivery DROP CONSTRAINT FK_3781EC108D9F6D38');
        $this->addSql('ALTER TABLE sylius_adjustment DROP CONSTRAINT FK_ACA6E0F28D9F6D38');
        $this->addSql('ALTER TABLE sylius_order_event DROP CONSTRAINT FK_1F7207A3D0BBCCBE');
        $this->addSql('ALTER TABLE sylius_order_item DROP CONSTRAINT FK_77B587ED8D9F6D38');
        $this->addSql('ALTER TABLE sylius_payment DROP CONSTRAINT FK_D9191BD48D9F6D38');
        $this->addSql('ALTER TABLE sylius_adjustment DROP CONSTRAINT FK_ACA6E0F2E415FB15');
        $this->addSql('ALTER TABLE sylius_order_item_unit DROP CONSTRAINT FK_82BF226EE415FB15');
        $this->addSql('ALTER TABLE sylius_adjustment DROP CONSTRAINT FK_ACA6E0F2F720C233');
        $this->addSql('ALTER TABLE sylius_payment DROP CONSTRAINT FK_D9191BD419883967');
        $this->addSql('ALTER TABLE sylius_payment_method_translation DROP CONSTRAINT FK_966BE3A12C2AC5D3');
        $this->addSql('ALTER TABLE sylius_product_association DROP CONSTRAINT FK_48E9CDAB4584665A');
        $this->addSql('ALTER TABLE sylius_product_association_product DROP CONSTRAINT FK_A427B9834584665A');
        $this->addSql('ALTER TABLE sylius_product_attribute_value DROP CONSTRAINT FK_8A053E544584665A');
        $this->addSql('ALTER TABLE sylius_product_image DROP CONSTRAINT FK_88C64B2D4584665A');
        $this->addSql('ALTER TABLE sylius_product_options DROP CONSTRAINT FK_2B5FF0094584665A');
        $this->addSql('ALTER TABLE sylius_product_taxon DROP CONSTRAINT FK_169C6CD94584665A');
        $this->addSql('ALTER TABLE sylius_product_translation DROP CONSTRAINT FK_105A9082C2AC5D3');
        $this->addSql('ALTER TABLE sylius_product_variant DROP CONSTRAINT FK_A29B5234584665A');
        $this->addSql('ALTER TABLE sylius_product_association_product DROP CONSTRAINT FK_A427B983EFB9C8A5');
        $this->addSql('ALTER TABLE sylius_product_association DROP CONSTRAINT FK_48E9CDABB1E1C39');
        $this->addSql('ALTER TABLE sylius_product_association_type_translation DROP CONSTRAINT FK_4F618E52C2AC5D3');
        $this->addSql('ALTER TABLE sylius_product_attribute_translation DROP CONSTRAINT FK_93850EBA2C2AC5D3');
        $this->addSql('ALTER TABLE sylius_product_attribute_value DROP CONSTRAINT FK_8A053E54B6E62EFA');
        $this->addSql('ALTER TABLE sylius_product_option_translation DROP CONSTRAINT FK_CBA491AD2C2AC5D3');
        $this->addSql('ALTER TABLE sylius_product_option_value DROP CONSTRAINT FK_F7FF7D4BA7C41D6F');
        $this->addSql('ALTER TABLE sylius_product_options DROP CONSTRAINT FK_2B5FF009A7C41D6F');
        $this->addSql('ALTER TABLE sylius_product_option_value_translation DROP CONSTRAINT FK_8D4382DC2C2AC5D3');
        $this->addSql('ALTER TABLE sylius_product_variant_option_value DROP CONSTRAINT FK_76CDAFA1D957CA06');
        $this->addSql('ALTER TABLE sylius_order_item DROP CONSTRAINT FK_77B587ED3B69A9AF');
        $this->addSql('ALTER TABLE sylius_product_variant_option_value DROP CONSTRAINT FK_76CDAFA13B69A9AF');
        $this->addSql('ALTER TABLE sylius_product_variant_translation DROP CONSTRAINT FK_8DC18EDC2C2AC5D3');
        $this->addSql('ALTER TABLE business_taxon DROP CONSTRAINT FK_2586C414DE13F470');
        $this->addSql('ALTER TABLE listing_taxon DROP CONSTRAINT FK_AD89FB27DE13F470');
        $this->addSql('ALTER TABLE sylius_product_taxon DROP CONSTRAINT FK_169C6CD9DE13F470');
        $this->addSql('ALTER TABLE sylius_taxon DROP CONSTRAINT FK_CFD811CAA977936C');
        $this->addSql('ALTER TABLE sylius_taxon DROP CONSTRAINT FK_CFD811CA727ACA70');
        $this->addSql('ALTER TABLE sylius_taxon_translation DROP CONSTRAINT FK_1487DFCF2C2AC5D3');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB254F382B24');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25BC2D6B55');
        $this->addSql('ALTER TABLE task_collection_item DROP CONSTRAINT FK_13199EFF8DB60186');
        $this->addSql('ALTER TABLE delivery DROP CONSTRAINT FK_3781EC10BF396750');
        $this->addSql('ALTER TABLE task_collection_item DROP CONSTRAINT FK_13199EFF727ACA70');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDE1F55203D');
        $this->addSql('ALTER TABLE post DROP CONSTRAINT FK_5A8A6C8D1F55203D');
        $this->addSql('ALTER TABLE topic_followers DROP CONSTRAINT FK_6D9D691F1F55203D');
        $this->addSql('DROP TABLE address');
        $this->addSql('DROP TABLE api_app');
        $this->addSql('DROP TABLE api_user');
        $this->addSql('DROP TABLE api_user_business');
        $this->addSql('DROP TABLE booking');
        $this->addSql('DROP TABLE business');
        $this->addSql('DROP TABLE business_fulfillment_methods');
        $this->addSql('DROP TABLE business_closing_rule');
        $this->addSql('DROP TABLE business_taxon');
        $this->addSql('DROP TABLE business_fulfillment_method');
        $this->addSql('DROP TABLE closing_rule');
        $this->addSql('DROP TABLE craue_config_setting');
        $this->addSql('DROP TABLE delivery');
        $this->addSql('DROP TABLE listing');
        $this->addSql('DROP TABLE listing_taxon');
        $this->addSql('DROP TABLE listing_availability');
        $this->addSql('DROP TABLE listing_image');
        $this->addSql('DROP TABLE listing_pricing_rule');
        $this->addSql('DROP TABLE listing_pricing_rule_set');
        $this->addSql('DROP TABLE listing_review');
        $this->addSql('DROP TABLE listing_subscription');
        $this->addSql('DROP TABLE listing_translation');
        $this->addSql('DROP TABLE post');
        $this->addSql('DROP TABLE sylius_adjustment');
        $this->addSql('DROP TABLE sylius_channel');
        $this->addSql('DROP TABLE sylius_currency');
        $this->addSql('DROP TABLE sylius_customer');
        $this->addSql('DROP TABLE sylius_customer_address');
        $this->addSql('DROP TABLE sylius_customer_group');
        $this->addSql('DROP TABLE sylius_exchange_rate');
        $this->addSql('DROP TABLE sylius_locale');
        $this->addSql('DROP TABLE sylius_order');
        $this->addSql('DROP TABLE sylius_order_event');
        $this->addSql('DROP TABLE sylius_order_item');
        $this->addSql('DROP TABLE sylius_order_item_unit');
        $this->addSql('DROP TABLE sylius_order_sequence');
        $this->addSql('DROP TABLE sylius_payment');
        $this->addSql('DROP TABLE sylius_payment_method');
        $this->addSql('DROP TABLE sylius_payment_method_translation');
        $this->addSql('DROP TABLE sylius_product');
        $this->addSql('DROP TABLE sylius_product_association');
        $this->addSql('DROP TABLE sylius_product_association_product');
        $this->addSql('DROP TABLE sylius_product_association_type');
        $this->addSql('DROP TABLE sylius_product_association_type_translation');
        $this->addSql('DROP TABLE sylius_product_attribute');
        $this->addSql('DROP TABLE sylius_product_attribute_translation');
        $this->addSql('DROP TABLE sylius_product_attribute_value');
        $this->addSql('DROP TABLE sylius_product_image');
        $this->addSql('DROP TABLE sylius_product_option');
        $this->addSql('DROP TABLE sylius_product_option_translation');
        $this->addSql('DROP TABLE sylius_product_option_value');
        $this->addSql('DROP TABLE sylius_product_option_value_translation');
        $this->addSql('DROP TABLE sylius_product_options');
        $this->addSql('DROP TABLE sylius_product_taxon');
        $this->addSql('DROP TABLE sylius_product_translation');
        $this->addSql('DROP TABLE sylius_product_variant');
        $this->addSql('DROP TABLE sylius_product_variant_option_value');
        $this->addSql('DROP TABLE sylius_product_variant_translation');
        $this->addSql('DROP TABLE sylius_taxon');
        $this->addSql('DROP TABLE sylius_taxon_translation');
        $this->addSql('DROP TABLE task');
        $this->addSql('DROP TABLE task_collection');
        $this->addSql('DROP TABLE task_collection_item');
        $this->addSql('DROP TABLE topic');
        $this->addSql('DROP TABLE topic_followers');
        $this->addSql('DROP TABLE welldesign');
    }
}
