monolog:
  handlers:
    main:
      type: rotating_file
      path: "%env(APP_LOG_DIR)%/%kernel.environment%.log"
      level: debug
      max_files: 3
      channels: ["!event", "!api", "!stripe", "!loopeat"]
    console:
      type:   console
      channels: ["!event", "!doctrine"]
    api:
      type: rotating_file
      path: "%env(APP_LOG_DIR)%/api.%kernel.environment%.log"
      level: info
      formatter: monolog.formatter.json
      max_files: 3
      channels: [api]
